# Generated by Django 4.2.5 on 2023-10-23 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_comunicado_detalle_alter_comunicado_entidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='entidad',
            field=models.ForeignKey(help_text='Elija el departamento asociado', on_delete=django.db.models.deletion.CASCADE, to='core.entidad'),
        ),
    ]
