# Generated by Django 4.2.5 on 2023-10-24 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_comunicado_entidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entidad',
            options={'verbose_name': 'Entidad', 'verbose_name_plural': 'Entidades'},
        ),
    ]
