# Generated by Django 4.2.5 on 2023-10-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comunicado_modificado_por_comunicado_publicado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='tipo',
            field=models.CharField(choices=[('S', 'Suspensión de actividades'), ('C', 'Suspensión de clases'), ('I', 'Información'), ('-', 'Seleccionar')], default='-', max_length=20),
        ),
    ]
